#!/usr/bin/env bash
# Write a Bash script that:
# 	Creates the file /var/run/myscript.pid containing its PID
# 	Displays To infinity and beyond indefinitely
# 	Displays I hate the kill command when receiving a SIGTERM signal
# 	Displays Y U no love me?! when receiving a SIGINT signal
# 	Deletes the file /var/run/myscript.pid and terminates itself 
#	when receiving a SIGQUIT or SIGTERM signal

sudo touch "/var/run/myscript.pid"
echo $$ | sudo tee /var/run/myscript.pid >/dev/null

while true; do
	trap "echo I hate the kill command&& sudo  rm -rf /var/run/myscript.pid && exit" SIGTERM
	trap "echo Y U no love me?! && sudo rm -rf /var/run/myscript.pid && exit" SIGINT
	echo "To infinity and beyond"
	sleep 5
done