#!/usr/bin/env bash
# Write a Bash script that:
# 	Creates the file /var/run/myscript.pid containing its PID
# 	Displays To infinity and beyond indefinitely
# 	Displays I hate the kill command when receiving a SIGTERM signal
# 	Displays Y U no love me?! when receiving a SIGINT signal
# 	Deletes the file /var/run/myscript.pid and terminates itself 
#	when receiving a SIGQUIT or SIGTERM signal

touch "/var/run/myscript.pid"
while true; do
	trap "echo I hate the kill command && exit && rm -rf /var/run/myscript.pid" SIGTERM
	trap "echo Y U no love me?! && exit" SIGINT
	echo "To infinity and beyond"
	sleep 1
done