#!/usr/bin/env bash
# Write a Bash script that displays:
# 	To infinity and beyond indefinitely
# 	With a sleep 2 in between each iteration
# 	I am invincible!!! when receiving a SIGTERM signal
function handleSignal()
{
	echo "I am invincible!!!"
}

while true; do
	trap handleSignal SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
